'use client';
import React, { useState, useEffect } from 'react';
import {
  Play,
  BookOpen,
  Shield,
  Smartphone,
  Brain,
  ArrowRight,
  Menu,
  X,
  Moon,
  Sun,
} from 'lucide-react';

// Type for isVisible state
interface IsVisibleMap {
  [key: string]: boolean;
}

const HomePage = () => {
  const [isMenuOpen, setIsMenuOpen] = useState(false);
  const [isDarkMode, setIsDarkMode] = useState(false);
  const [scrollY, setScrollY] = useState(0);
  const [isVisible, setIsVisible] = useState<IsVisibleMap>({});

  useEffect(() => {
    const handleScroll = () => setScrollY(window.scrollY);
    window.addEventListener('scroll', handleScroll);
    return () => window.removeEventListener('scroll', handleScroll);
  }, []);

  useEffect(() => {
    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          setIsVisible((prev) => ({
            ...prev,
            [entry.target.id]: entry.isIntersecting,
          }));
        });
      },
      { threshold: 0.1 },
    );

    const elements = document.querySelectorAll('[id^="animate-"]');
    elements.forEach((el) => observer.observe(el));

    return () => observer.disconnect();
  }, []);

  const toggleDarkMode = () => {
    setIsDarkMode(!isDarkMode);
    document.documentElement.classList.toggle('dark');
  };

  const codeSnippet = `const learningPlatform = {
  name: 'EduCraft',
  features: ['Progress Tracking', 'AI Summaries', 'Dark Mode'],
  mission: 'Making learning effortless and accessible',
  technology: 'Next.js + TypeScript + Tailwind',
  
  getStarted: function() {
    return 'Ready to transform your learning journey?';
  }
};`;

  const features = [
    {
      icon: <BookOpen className="w-5 h-5" />,
      title: 'Effortless Learning Experience',
      description:
        'Pick up where you left off with automatic progress tracking and a clean, focused interface.',
      tech: 'React + Supabase',
    },
    {
      icon: <Brain className="w-5 h-5" />,
      title: 'AI-Powered Learning',
      description:
        'Get personalized lesson summaries and smart quizzes generated by AI to enhance your understanding.',
      tech: 'OpenAI + Vector DB',
    },
    {
      icon: <Shield className="w-5 h-5" />,
      title: 'Secure & Private',
      description:
        'Your learning data is protected with enterprise-grade security and privacy controls.',
      tech: 'Auth0 + Encryption',
    },
    {
      icon: <Smartphone className="w-5 h-5" />,
      title: 'Cross-Platform Ready',
      description:
        'Seamlessly switch between desktop, tablet, and mobile with responsive design and PWA support.',
      tech: 'PWA + Responsive',
    },
  ];

  const stats = [
    { number: '10,000+', label: 'Active Learners', desc: 'Students worldwide' },
    { number: '500+', label: 'Mini Courses', desc: 'Curated content' },
    { number: '98%', label: 'Completion Rate', desc: 'Student success' },
    { number: '4.9/5', label: 'Average Rating', desc: 'User satisfaction' },
  ];

  const testimonials = [
    {
      quote:
        'EduCraft has completely transformed how I approach learning. The AI summaries and progress tracking keep me motivated and on track.',
      name: 'Sarah Chen',
      role: 'Product Designer at Stripe',
      avatar: 'SC',
    },
    {
      quote:
        "As a developer, I appreciate the clean UX and performance. It's exactly what modern learners need - no fluff, just results.",
      name: 'Marcus Rodriguez',
      role: 'Senior Engineer at Vercel',
      avatar: 'MR',
    },
  ];

  return (
    <div
      className={`min-h-screen transition-all duration-300 ${
        isDarkMode ? 'dark bg-gray-900 text-gray-100' : 'bg-white text-gray-900'
      }`}
      style={{
        fontFamily: 'Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
      }}
    >
      {/* Navigation */}
      <nav
        className={`fixed top-0 w-full z-50 transition-all duration-300 ${
          scrollY > 20
            ? `backdrop-blur-xl ${
                isDarkMode ? 'bg-gray-900/80 border-gray-800' : 'bg-white/80 border-gray-200'
              } border-b`
            : 'bg-transparent'
        }`}
      >
        <div className="max-w-6xl mx-auto px-6 lg:px-8">
          <div className="flex justify-between items-center h-16">
            <div className="flex items-center space-x-3">
              <div className="w-8 h-8 bg-gray-900 dark:bg-white rounded-md flex items-center justify-center">
                <BookOpen className="w-4 h-4 text-white dark:text-gray-900" />
              </div>
              <span className="text-lg font-semibold">EduCraft</span>
            </div>

            <div className="hidden md:flex items-center space-x-8">
              <a
                href="#features"
                className="text-sm text-gray-600 dark:text-gray-400 hover:text-gray-900 dark:hover:text-gray-100 transition-colors"
              >
                Features
              </a>
              <a
                href="#about"
                className="text-sm text-gray-600 dark:text-gray-400 hover:text-gray-900 dark:hover:text-gray-100 transition-colors"
              >
                About
              </a>
              <a
                href="#testimonials"
                className="text-sm text-gray-600 dark:text-gray-400 hover:text-gray-900 dark:hover:text-gray-100 transition-colors"
              >
                Reviews
              </a>
              <button
                onClick={toggleDarkMode}
                className="p-2 rounded-md hover:bg-gray-100 dark:hover:bg-gray-800 transition-colors"
                aria-label="Toggle dark mode"
              >
                {isDarkMode ? <Sun className="w-4 h-4" /> : <Moon className="w-4 h-4" />}
              </button>
              <button className="bg-gray-900 dark:bg-white text-white dark:text-gray-900 px-4 py-2 rounded-md text-sm font-medium hover:bg-gray-800 dark:hover:bg-gray-100 transition-colors">
                Get Started
              </button>
            </div>

            <button
              className="md:hidden p-2 rounded-md hover:bg-gray-100 dark:hover:bg-gray-800 transition-colors"
              onClick={() => setIsMenuOpen(!isMenuOpen)}
              aria-label="Toggle menu"
            >
              {isMenuOpen ? <X className="w-5 h-5" /> : <Menu className="w-5 h-5" />}
            </button>
          </div>
        </div>
      </nav>

      {/* Mobile Menu */}
      <div
        className={`fixed top-16 left-0 right-0 z-40 transform transition-all duration-200 ${
          isMenuOpen ? 'translate-y-0 opacity-100' : '-translate-y-full opacity-0'
        } ${isDarkMode ? 'bg-gray-900' : 'bg-white'} border-b ${isDarkMode ? 'border-gray-800' : 'border-gray-200'}`}
      >
        <div className="px-6 py-4 space-y-4">
          <a href="#features" className="block py-2 text-sm hover:text-gray-600 transition-colors">
            Features
          </a>
          <a href="#about" className="block py-2 text-sm hover:text-gray-600 transition-colors">
            About
          </a>
          <a
            href="#testimonials"
            className="block py-2 text-sm hover:text-gray-600 transition-colors"
          >
            Reviews
          </a>
          <button className="w-full bg-gray-900 dark:bg-white text-white dark:text-gray-900 px-4 py-2 rounded-md text-sm font-medium">
            Get Started
          </button>
        </div>
      </div>

      {/* Hero Section */}
      <section className="pt-32 pb-20 px-6 lg:px-8">
        <div className="max-w-6xl mx-auto">
          <div className="max-w-3xl">
            <h1
              id="animate-title"
              className={`text-4xl lg:text-6xl font-bold leading-tight mb-6 transition-all duration-1000 ${
                isVisible['animate-title'] ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-4'
              }`}
            >
              Building learning experiences with{' '}
              <span className="text-gray-600 dark:text-gray-400">code and creativity</span>
            </h1>

            <p
              id="animate-subtitle"
              className={`text-xl text-gray-600 dark:text-gray-400 mb-8 leading-relaxed max-w-2xl transition-all duration-1000 delay-200 ${
                isVisible['animate-subtitle']
                  ? 'opacity-100 translate-y-0'
                  : 'opacity-0 translate-y-4'
              }`}
            >
              A modern, production-grade mini course platform specializing in creating elegant,
              high-performance learning experiences that solve real educational challenges.
            </p>

            <div
              id="animate-buttons"
              className={`flex flex-col sm:flex-row gap-4 mb-16 transition-all duration-1000 delay-400 ${
                isVisible['animate-buttons']
                  ? 'opacity-100 translate-y-0'
                  : 'opacity-0 translate-y-4'
              }`}
            >
              <button className="group bg-gray-900 dark:bg-white text-white dark:text-gray-900 px-6 py-3 rounded-md font-medium hover:bg-gray-800 dark:hover:bg-gray-100 transition-all duration-200 flex items-center justify-center">
                Start Learning Today
                <ArrowRight className="ml-2 w-4 h-4 group-hover:translate-x-0.5 transition-transform" />
              </button>
              <button className="group flex items-center justify-center px-6 py-3 text-gray-600 dark:text-gray-400 hover:text-gray-900 dark:hover:text-gray-100 transition-colors">
                <Play className="mr-2 w-4 h-4" />
                Watch Demo
              </button>
            </div>

            {/* Code Block */}
            <div
              id="animate-code"
              className={`transition-all duration-1000 delay-600 ${
                isVisible['animate-code'] ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-4'
              }`}
            >
              <pre
                className={`p-6 rounded-lg text-sm font-mono overflow-x-auto ${
                  isDarkMode ? 'bg-gray-800 text-gray-300' : 'bg-gray-50 text-gray-700'
                }`}
              >
                <code>{codeSnippet}</code>
              </pre>
            </div>
          </div>
        </div>
      </section>

      {/* Stats Section */}
      <section className="py-16 px-6 lg:px-8">
        <div className="max-w-6xl mx-auto">
          <div
            id="animate-stats"
            className={`grid grid-cols-2 lg:grid-cols-4 gap-8 transition-all duration-1000 ${
              isVisible['animate-stats'] ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-4'
            }`}
          >
            {stats.map((stat, index) => (
              <div key={index} className="text-center lg:text-left">
                <div className="text-2xl lg:text-3xl font-bold mb-2">{stat.number}</div>
                <div className="text-sm font-medium text-gray-900 dark:text-gray-100 mb-1">
                  {stat.label}
                </div>
                <div className="text-sm text-gray-600 dark:text-gray-400">{stat.desc}</div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* About Section */}
      <section id="about" className="py-20 px-6 lg:px-8">
        <div className="max-w-6xl mx-auto">
          <div className="grid lg:grid-cols-2 gap-16 items-center">
            <div>
              <h2
                id="animate-about-title"
                className={`text-3xl lg:text-4xl font-bold mb-6 transition-all duration-1000 ${
                  isVisible['animate-about-title']
                    ? 'opacity-100 translate-y-0'
                    : 'opacity-0 translate-y-4'
                }`}
              >
                Who We Are & What We Do
              </h2>
              <p
                id="animate-about-desc"
                className={`text-gray-600 dark:text-gray-400 mb-6 leading-relaxed transition-all duration-1000 delay-200 ${
                  isVisible['animate-about-desc']
                    ? 'opacity-100 translate-y-0'
                    : 'opacity-0 translate-y-4'
                }`}
              >
                We&apos;re passionate educators and developers with 7+ years of experience building
                exceptional digital learning experiences.
              </p>
              <p
                id="animate-about-desc2"
                className={`text-gray-600 dark:text-gray-400 mb-8 leading-relaxed transition-all duration-1000 delay-300 ${
                  isVisible['animate-about-desc2']
                    ? 'opacity-100 translate-y-0'
                    : 'opacity-0 translate-y-4'
                }`}
              >
                Our approach combines technical expertise with deep understanding of learning
                psychology to deliver platforms that not only function flawlessly but provide
                exceptional educational outcomes.
              </p>
            </div>
            <div
              id="animate-about-image"
              className={`transition-all duration-1000 delay-400 ${
                isVisible['animate-about-image']
                  ? 'opacity-100 translate-y-0'
                  : 'opacity-0 translate-y-4'
              }`}
            >
              <div
                className={`aspect-square rounded-lg ${isDarkMode ? 'bg-gray-800' : 'bg-gray-100'} flex items-center justify-center`}
              >
                <BookOpen className="w-16 h-16 text-gray-400" />
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section id="features" className="py-20 px-6 lg:px-8">
        <div className="max-w-6xl mx-auto">
          <div
            id="animate-features-title"
            className={`mb-16 transition-all duration-1000 ${
              isVisible['animate-features-title']
                ? 'opacity-100 translate-y-0'
                : 'opacity-0 translate-y-4'
            }`}
          >
            <h2 className="text-3xl lg:text-4xl font-bold mb-4">Core Expertise</h2>
            <p className="text-gray-600 dark:text-gray-400 text-lg">
              Technologies and features that power our platform
            </p>
          </div>

          <div className="grid lg:grid-cols-2 gap-8">
            {features.map((feature, index) => (
              <div
                key={index}
                id={`animate-feature-${index}`}
                className={`group p-8 rounded-lg transition-all duration-700 hover:bg-gray-50 dark:hover:bg-gray-800/50 ${
                  isVisible[`animate-feature-${index}`]
                    ? 'opacity-100 translate-y-0'
                    : 'opacity-0 translate-y-4'
                }`}
                style={{ transitionDelay: `${index * 100}ms` }}
              >
                <div className="flex items-center mb-4">
                  <div className="p-2 bg-gray-900 dark:bg-white rounded-md mr-3">
                    {React.cloneElement(feature.icon, {
                      className: 'w-5 h-5 text-white dark:text-gray-900',
                    })}
                  </div>
                  <h3 className="text-lg font-semibold">{feature.title}</h3>
                </div>
                <p className="text-gray-600 dark:text-gray-400 mb-4 leading-relaxed">
                  {feature.description}
                </p>
                <div className="text-sm text-gray-500 dark:text-gray-500 font-mono">
                  {feature.tech}
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Testimonials Section */}
      <section id="testimonials" className="py-20 px-6 lg:px-8">
        <div className="max-w-6xl mx-auto">
          <div
            id="animate-testimonials-title"
            className={`mb-16 transition-all duration-1000 ${
              isVisible['animate-testimonials-title']
                ? 'opacity-100 translate-y-0'
                : 'opacity-0 translate-y-4'
            }`}
          >
            <h2 className="text-3xl lg:text-4xl font-bold mb-4">What People Say</h2>
            <p className="text-gray-600 dark:text-gray-400 text-lg">
              Feedback from learners and professionals
            </p>
          </div>

          <div className="grid lg:grid-cols-2 gap-8">
            {testimonials.map((testimonial, index) => (
              <div
                key={index}
                id={`animate-testimonial-${index}`}
                className={`p-8 rounded-lg border transition-all duration-700 ${
                  isVisible[`animate-testimonial-${index}`]
                    ? 'opacity-100 translate-y-0'
                    : 'opacity-0 translate-y-4'
                } ${isDarkMode ? 'border-gray-800 bg-gray-800/20' : 'border-gray-200 bg-gray-50/50'}`}
                style={{ transitionDelay: `${index * 200}ms` }}
              >
                <p className="text-gray-600 dark:text-gray-400 mb-6 leading-relaxed italic">
                  &quot;{testimonial.quote}&quot;
                </p>
                <div className="flex items-center">
                  <div className="w-10 h-10 bg-gray-900 dark:bg-white rounded-full flex items-center justify-center mr-3">
                    <span className="text-white dark:text-gray-900 text-sm font-semibold">
                      {testimonial.avatar}
                    </span>
                  </div>
                  <div>
                    <div className="font-semibold">{testimonial.name}</div>
                    <div className="text-sm text-gray-600 dark:text-gray-400">
                      {testimonial.role}
                    </div>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section
        id="animate-cta"
        className={`py-20 px-6 lg:px-8 transition-all duration-1000 ${
          isVisible['animate-cta'] ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-4'
        }`}
      >
        <div className="max-w-6xl mx-auto text-center">
          <h2 className="text-3xl lg:text-4xl font-bold mb-6">Let&apos;s Work Together</h2>
          <p className="text-xl text-gray-600 dark:text-gray-400 mb-8 max-w-2xl mx-auto">
            Ready to transform your learning journey? Let&apos;s discuss how our platform can help
            you achieve your goals.
          </p>

          <div className="flex flex-col sm:flex-row gap-4 justify-center mb-12">
            <button className="bg-gray-900 dark:bg-white text-white dark:text-gray-900 px-6 py-3 rounded-md font-medium hover:bg-gray-800 dark:hover:bg-gray-100 transition-colors">
              Get Started Free
            </button>
            <button className="px-6 py-3 text-gray-600 dark:text-gray-400 hover:text-gray-900 dark:hover:text-gray-100 transition-colors border border-gray-300 dark:border-gray-700 rounded-md">
              Schedule a Demo
            </button>
          </div>

          <div className="text-sm text-gray-600 dark:text-gray-400">
            <div className="font-semibold mb-2">Availability</div>
            <div>Currently available for new learners and institutional partnerships.</div>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer
        className={`py-12 px-6 lg:px-8 border-t ${isDarkMode ? 'border-gray-800' : 'border-gray-200'}`}
      >
        <div className="max-w-6xl mx-auto">
          <div className="flex flex-col md:flex-row justify-between items-center">
            <div className="flex items-center space-x-3 mb-4 md:mb-0">
              <div className="w-6 h-6 bg-gray-900 dark:bg-white rounded-md flex items-center justify-center">
                <BookOpen className="w-3 h-3 text-white dark:text-gray-900" />
              </div>
              <span className="font-semibold">EduCraft</span>
            </div>

            <div className="text-sm text-gray-600 dark:text-gray-400">
              © 2025 EduCraft. Built with ❤️ for the learning community.
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
};

export default HomePage;
